//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelExport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        public int FlatSK { get; set; }
        public string Code { get; set; }
        public string Vendor { get; set; }
        public string Side { get; set; }
        public byte District { get; set; }
        public bool Elevator { get; set; }
        public decimal NumberOfRooms { get; set; }
        public short FloorArea { get; set; }
        public decimal Price { get; set; }
    }
}
